spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exceptions
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update