spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exceptions
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
resilience4j:
  circuitbreaker:
    instances:
      userClient:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
        eventConsumerBufferSize: 10
  timelimiter:
    instances:
      userClient:
        timeoutDuration: 1s
